# Spring Application Configuration
spring.application.name=berlin-clock

# Server Configuration
server.port=8080

# Logging Configuration
logging.level.root=INFO
logging.level.com.bnppf.kata.berlinclock=DEBUG

# Error Handling
server.error.include-message=always
server.error.include-stacktrace=never